version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "passwords_db"
      POSTGRES_USER: "pass_admin"
      POSTGRES_PASSWORD: "BqQBWxQa2-3tRse"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
